feat(FSADT1-499): adding vault broker api
bcgov/nr-forest-client-api pull request #94
Opened 2023-01-30 17:04 UTC by paulushcgcj

# Description

Adding support for the vault broker API

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Further comments

Testing broker API for release

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[API](https://nr-forest-client-api-94-backend.apps.silver.devops.gov.bc.ca/) available

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-forest-client-api/actions/workflows/merge-main.yml)

2023-01-30 17:11 UTC, DerekRoberts approved these changes
Looks good!

2023-01-30 17:15 UTC, DerekRoberts requested changes

2023-01-30 17:15 UTC, DerekRoberts commented on .github/workflows/pr-open.yml
> +          # Read the intention file and replace the event url and the user id
Please address coding consistency, like trailing right brackets.  Some lines have a break before, some don't.  There is also inconsistency in where lines are broken and length, like INTENTION vs VAULT_TOKEN_WRAP.

2023-01-31 23:56 UTC, DerekRoberts approved these changes
New action! Very cool. :)

2023-02-01 00:03 UTC, mamartinezmejia approved these changes

2023-02-01 00:04 UTC, merged